// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: ptypes/jwt.proto

package ptypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Kty string `protobuf:"bytes,2,opt,name=kty,proto3" json:"kty,omitempty"`
	Alg string `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
	Use string `protobuf:"bytes,4,opt,name=use,proto3" json:"use,omitempty"`
	X5T string `protobuf:"bytes,5,opt,name=x5t,proto3" json:"x5t,omitempty"`
	E   string `protobuf:"bytes,6,opt,name=e,proto3" json:"e,omitempty"`
	N   string `protobuf:"bytes,7,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *JwtPublicKey) Reset() {
	*x = JwtPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ptypes_jwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtPublicKey) ProtoMessage() {}

func (x *JwtPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_ptypes_jwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtPublicKey.ProtoReflect.Descriptor instead.
func (*JwtPublicKey) Descriptor() ([]byte, []int) {
	return file_ptypes_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *JwtPublicKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *JwtPublicKey) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *JwtPublicKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *JwtPublicKey) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *JwtPublicKey) GetX5T() string {
	if x != nil {
		return x.X5T
	}
	return ""
}

func (x *JwtPublicKey) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *JwtPublicKey) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

type JwtPublicCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID
	Kid  string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Cert string `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *JwtPublicCert) Reset() {
	*x = JwtPublicCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ptypes_jwt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtPublicCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtPublicCert) ProtoMessage() {}

func (x *JwtPublicCert) ProtoReflect() protoreflect.Message {
	mi := &file_ptypes_jwt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtPublicCert.ProtoReflect.Descriptor instead.
func (*JwtPublicCert) Descriptor() ([]byte, []int) {
	return file_ptypes_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *JwtPublicCert) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *JwtPublicCert) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

type ListJwtPublicKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys        []*JwtPublicKey  `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	PublicCert  *JwtPublicCert   `protobuf:"bytes,2,opt,name=public_cert,json=publicCert,proto3" json:"public_cert,omitempty"`
	PublicCerts []*JwtPublicCert `protobuf:"bytes,3,rep,name=public_certs,json=publicCerts,proto3" json:"public_certs,omitempty"`
}

func (x *ListJwtPublicKeysResponse) Reset() {
	*x = ListJwtPublicKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ptypes_jwt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJwtPublicKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJwtPublicKeysResponse) ProtoMessage() {}

func (x *ListJwtPublicKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ptypes_jwt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJwtPublicKeysResponse.ProtoReflect.Descriptor instead.
func (*ListJwtPublicKeysResponse) Descriptor() ([]byte, []int) {
	return file_ptypes_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *ListJwtPublicKeysResponse) GetKeys() []*JwtPublicKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListJwtPublicKeysResponse) GetPublicCert() *JwtPublicCert {
	if x != nil {
		return x.PublicCert
	}
	return nil
}

func (x *ListJwtPublicKeysResponse) GetPublicCerts() []*JwtPublicCert {
	if x != nil {
		return x.PublicCerts
	}
	return nil
}

var File_ptypes_jwt_proto protoreflect.FileDescriptor

var file_ptypes_jwt_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x0c,
	0x4a, 0x77, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x74, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x6c, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x35, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x78, 0x35, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x6e, 0x22, 0x35, 0x0a, 0x0d, 0x4a, 0x77, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x43,
	0x65, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0xba, 0x01, 0x0a, 0x19, 0x4c, 0x69,
	0x73, 0x74, 0x4a, 0x77, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x2e,
	0x4a, 0x77, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x63, 0x65, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77,
	0x74, 0x2e, 0x4a, 0x77, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x43, 0x65, 0x72, 0x74, 0x52,
	0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x43, 0x65, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x4a, 0x77, 0x74, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x43, 0x65, 0x72, 0x74, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x43, 0x65, 0x72, 0x74, 0x73, 0x42, 0x6a, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6a, 0x77, 0x74, 0x42, 0x08, 0x4a, 0x77, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x14, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x70, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x41, 0x4a, 0x58, 0xaa, 0x02, 0x07,
	0x41, 0x70, 0x69, 0x2e, 0x4a, 0x77, 0x74, 0xca, 0x02, 0x07, 0x41, 0x70, 0x69, 0x5c, 0x4a, 0x77,
	0x74, 0xe2, 0x02, 0x13, 0x41, 0x70, 0x69, 0x5c, 0x4a, 0x77, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x41, 0x70, 0x69, 0x3a, 0x3a, 0x4a,
	0x77, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ptypes_jwt_proto_rawDescOnce sync.Once
	file_ptypes_jwt_proto_rawDescData = file_ptypes_jwt_proto_rawDesc
)

func file_ptypes_jwt_proto_rawDescGZIP() []byte {
	file_ptypes_jwt_proto_rawDescOnce.Do(func() {
		file_ptypes_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_ptypes_jwt_proto_rawDescData)
	})
	return file_ptypes_jwt_proto_rawDescData
}

var file_ptypes_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ptypes_jwt_proto_goTypes = []interface{}{
	(*JwtPublicKey)(nil),              // 0: api.jwt.JwtPublicKey
	(*JwtPublicCert)(nil),             // 1: api.jwt.JwtPublicCert
	(*ListJwtPublicKeysResponse)(nil), // 2: api.jwt.ListJwtPublicKeysResponse
}
var file_ptypes_jwt_proto_depIdxs = []int32{
	0, // 0: api.jwt.ListJwtPublicKeysResponse.keys:type_name -> api.jwt.JwtPublicKey
	1, // 1: api.jwt.ListJwtPublicKeysResponse.public_cert:type_name -> api.jwt.JwtPublicCert
	1, // 2: api.jwt.ListJwtPublicKeysResponse.public_certs:type_name -> api.jwt.JwtPublicCert
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ptypes_jwt_proto_init() }
func file_ptypes_jwt_proto_init() {
	if File_ptypes_jwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ptypes_jwt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ptypes_jwt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtPublicCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ptypes_jwt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJwtPublicKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ptypes_jwt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ptypes_jwt_proto_goTypes,
		DependencyIndexes: file_ptypes_jwt_proto_depIdxs,
		MessageInfos:      file_ptypes_jwt_proto_msgTypes,
	}.Build()
	File_ptypes_jwt_proto = out.File
	file_ptypes_jwt_proto_rawDesc = nil
	file_ptypes_jwt_proto_goTypes = nil
	file_ptypes_jwt_proto_depIdxs = nil
}
